########## STEP 1
FROM node:14.2 as node
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build -- --prod



########## STEP 2
FROM nginx:alpine
VOLUME /var/cache/nginx
COPY ./nginx/default.conf /etc/nginx/conf.d
COPY --from=node /app/dist/LeGrandJour /usr/share/nginx/html